### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'serialized_options'

### ISSUE THREAD

**Issue by yourbuddy25** [ClaudiuGeorgiu/PlaystoreDownloader#32]
Hey,

I am getting this error when running the download.py file.
I properly installed python 3.8 but still the error is there.
I installed the requirements with **pip3 install -r requirements.txt** as **python3.8 -m pip install -r requirements.txt** gave this error
ERROR : 
```
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/usr/lib/python3/dist-packages/pip/__init__.py", line 29, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 23, in <module>
    from pip.locations import (
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 9, in <module>
    from distutils import sysconfig
ImportError: cannot import name 'sysconfig' from 'distutils' (/usr/lib/python3.8/distutils/__init__.py)

```

FULL ERROR :
```
Traceback (most recent call last):
  File "download.py", line 10, in <module>
    from playstore.playstore import Playstore
  File "/home/jatin/Documents/tools/PlaystoreDownloader/playstore/playstore.py", line 14, in <module>
    from playstore import playstore_proto_pb2 as playstore_protobuf
  File "/home/jatin/Documents/tools/PlaystoreDownloader/playstore/playstore_proto_pb2.py", line 17, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "download.py", line 10, in <module>
    from playstore.playstore import Playstore
  File "/home/jatin/Documents/tools/PlaystoreDownloader/playstore/playstore.py", line 14, in <module>
    from playstore import playstore_proto_pb2 as playstore_protobuf
  File "/home/jatin/Documents/tools/PlaystoreDownloader/playstore/playstore_proto_pb2.py", line 17, in <module>
    DESCRIPTOR = _descriptor.FileDescriptor(
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
 
```

**Comment by ClaudiuGeorgiu** [comment]
`ModuleNotFoundError: No module named 'apt_pkg'` looks like an error with the Python installation, sorry but I'm not able to replicate.
