### ISSUE TITLE
Error, el dispositivo no es compatible

### ISSUE THREAD

**Issue by noclastic** [ClaudiuGeorgiu/PlaystoreDownloader#35]
python3 download.py "com.google.android.googlequicksearchbox"
08/04/2020 12:56:41> [ERROR][playstore.playstore.Playstore][_download_with_progress()] Error for app 'com.google.android.googlequicksearchbox': Tu dispositivo no es compatible con este elemento.
08/04/2020 12:56:41> [ERROR][playstore.playstore.Playstore][download()] Error during the download: Error for app 'com.google.android.googlequicksearchbox': Tu dispositivo no es compatible con este elemento.
Traceback (most recent call last):
  File "/Users/noclastic/Downloads/arsenalOsint/PlaystoreDownloader/playstore/playstore.py", line 750, in download
    list(
  File "/Users/noclastic/Downloads/arsenalOsint/PlaystoreDownloader/playstore/playstore.py", line 282, in _download_with_progress
    raise RuntimeError(
RuntimeError: Error for app 'com.google.android.googlequicksearchbox': Tu dispositivo no es compatible con este elemento.
08/04/2020 12:56:41> [CRITICAL][__main__][main()] Error when downloading 'com.google.android.googlequicksearchbox'

Me es imposible descargar las apk. ¿Alguna solución a este error? Gracias. Un saludo

**Comment by noclastic** [comment]
Solucionado. Es cuestión de que solo me deja descargar las apps compatibles con la ID
