### ISSUE TITLE
"Your device is not compatible with this item."

### ISSUE THREAD

**Issue by eighthave** [ClaudiuGeorgiu/PlaystoreDownloader#42]
Using the Docker image, I've tried this with 3 working Google accounts each with their own Device ID.  I tried downloading ~20 different apps.  All of these combinations always end up with:

```console
# docker run -v "/tmp/tmp.KgE9sNyamy/credentials.json":"/app/credentials.json" -v /tmp/dl/:/app/Downloads/ --rm -it downloader org.mozilla.firefox
14/09/2020 10:39:29> [ERROR][playstore.playstore.Playstore][_handle_missing_payload()] Error for app 'org.mozilla.firefox': Your device is not compatible with this item.
14/09/2020 10:39:29> [ERROR][playstore.playstore.Playstore][download()] Error during the download: Error for app 'org.mozilla.firefox': Your device is not compatible with this item.
Traceback (most recent call last):
  File "/app/playstore/playstore.py", line 684, in download
    list(
  File "/app/playstore/playstore.py", line 322, in _download_with_progress
    _handle_missing_payload(response, package_name)
  File "/app/playstore/playstore.py", line 274, in _handle_missing_payload
    raise RuntimeError(
RuntimeError: Error for app 'org.mozilla.firefox': Your device is not compatible with this item.
14/09/2020 10:39:29> [CRITICAL][__main__][main()] Error when downloading 'org.mozilla.firefox'

```

**Comment by MouaadWeb** [comment]
Using direct code source, I'm facing the same problem.
Only same few apps can be downloaded and rest getting error message that the device is not compatible with this item. Even with apps that I already installed in my google accounts devices.
Any fix for that ?

**Comment by Exadra37** [comment]
Same here when using the docker image or by building from source, but I can install the app directly in the device.
