### ISSUE TITLE
DownloadAuthCookie was not received

### ISSUE THREAD

**Issue by muzzyrost** [ClaudiuGeorgiu/PlaystoreDownloader#55]
PlaystoreDownloader works without any issues for last days, but today I`ve go error almost for all apps:

```
28/05/2021 01:12:01> [ERROR][playstore.playstore.Playstore][_download_with_progress()] DownloadAuthCookie was not received for 'com.ohbibi.fps'
28/05/2021 01:12:01> [ERROR][playstore.playstore.Playstore][download()] Error during the download: DownloadAuthCookie was not received for 'com.ohbibi.fps'
Traceback (most recent call last):
  File "/PlaystoreDownloader/playstore/playstore.py", line 384, in _download_with_progress
    cookie = delivery_data.downloadAuthCookie[0]
IndexError: list index (0) out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/PlaystoreDownloader/playstore/playstore.py", line 719, in download
    list(
  File "/PlaystoreDownloader/playstore/playstore.py", line 389, in _download_with_progress
    raise RuntimeError(
RuntimeError: DownloadAuthCookie was not received for 'com.ohbibi.fps'
28/05/2021 01:12:01> [CRITICAL][__main__][main()] Error when downloading 'com.ohbibi.fps'
```

I`ve try few accounts but no luck.

**Comment by CaiMiao** [comment]
```
~/PlaystoreDownloader# pipenv run python download.py -c v8a-test.json -s jp.co.bandainamcoent.BNEI0242
21/09/2021 16:34:15> [ERROR][playstore.playstore.Playstore][_download_with_progress()] DownloadAuthCookie was not received for 'jp.co.bandainamcoent.BNEI0242'
21/09/2021 16:34:15> [ERROR][playstore.playstore.Playstore][download()] Error during the download: DownloadAuthCookie was not received for 'jp.co.bandainamcoent.BNEI0242'
Traceback (most recent call last):
  File "/root/PlaystoreDownloader/playstore/playstore.py", line 384, in _download_with_progress
    cookie = delivery_data.downloadAuthCookie[0]
IndexError: list index (0) out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/PlaystoreDownloader/playstore/playstore.py", line 725, in download
    show_progress_bar,
  File "/root/PlaystoreDownloader/playstore/playstore.py", line 390, in _download_with_progress
    f"DownloadAuthCookie was not received for '{package_name}'"
RuntimeError: DownloadAuthCookie was not received for 'jp.co.bandainamcoent.BNEI0242'
21/09/2021 16:34:15> [CRITICAL][__main__][main()] Error when downloading 'jp.co.bandainamcoent.BNEI0242'
```

same

**Comment by CaiMiao** [comment]
@muzzyrost  are you using the one from microG?

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/70
