### ISSUE TITLE
Error during the download: list index out of range

### ISSUE THREAD

**Issue by gl6692** [ClaudiuGeorgiu/PlaystoreDownloader#67]
I get this error when trying to download apps. I am using app password from Google. I also use Python 3.10.0, which may be causing the issue.

pipenv run py -m playstoredownloader.cli -b -s com.adobe.lrmobile
25/10/2021 09:17:25> [ERROR][playstoredownloader.playstore.playstore.Playstore][download()] Error during the download: list index out of range
Traceback (most recent call last):
  File "C:\Users\User\Downloads\playstoredownloader\PlaystoreDownloader\playstoredownloader\playstore\playstore.py", line 667, in download
    list(
  File "C:\Users\User\Downloads\playstoredownloader\PlaystoreDownloader\playstoredownloader\playstore\playstore.py", line 326, in _download_with_progress
    offer_type = meta.docV2.offer[0].offerType
  File "C:\Users\User\.virtualenvs\PlaystoreDownloader-uHkXu49V\lib\site-packages\google\protobuf\internal\containers.py", line 209, in __getitem__
    return self._values[key]
IndexError: list index out of range
25/10/2021 09:17:25> [ERROR][playstoredownloader.downloader.multi_downloader][download()] There was an error when downloading package com.adobe.lrmobile
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\Downloads\playstoredownloader\PlaystoreDownloader\playstoredownloader\cli\__main__.py", line 5, in <module>
    cli()
  File "C:\Users\User\Downloads\playstoredownloader\PlaystoreDownloader\playstoredownloader\cli\cli.py", line 8, in cli
    main(**vars(get_cmd_args()))
  File "C:\Users\User\Downloads\playstoredownloader\PlaystoreDownloader\playstoredownloader\downloader\main.py", line 25, in main
    return download_packages(package, blobs, split_apks, credentials, out_dir, tag)
  File "C:\Users\User\Downloads\playstoredownloader\PlaystoreDownloader\playstoredownloader\downloader\main.py", line 30, in download_packages
    return MultiDownloader(packages, downloader).download()
  File "C:\Users\User\Downloads\playstoredownloader\PlaystoreDownloader\playstoredownloader\downloader\multi_downloader.py", line 26, in download
    raise DownloadError()
playstoredownloader.downloader.downloader.DownloadError

**Comment by ClaudiuGeorgiu** [comment]
Tested on Windows 10 with Python 3.10 and I can't replicate the error.
