### ISSUE TITLE
Login success, but fail to download

### ISSUE THREAD

**Issue by 101142TS** [ClaudiuGeorgiu/PlaystoreDownloader#70]
Hi, I tried to do the download but it reported an error, the logs are

`25/11/2021 15:54:15> [ERROR][playstoredownloader.playstore.playstore.Playstore][download()] Error during the download: list index (0) out of range
Traceback (most recent call last):
  File "C:\Users\101142ts\Desktop\github\PlaystoreDownloader\playstoredownloader\playstore\playstore.py", line 669, in download
    list(
  File "C:\Users\101142ts\Desktop\github\PlaystoreDownloader\playstoredownloader\playstore\playstore.py", line 328, in _download_with_progress
    offer_type = meta.docV2.offer[0].offerType
IndexError: list index (0) out of range
25/11/2021 15:54:15> [ERROR][playstoredownloader.downloader.multi_downloader][download()] There was an error when downloading package org.videolan.vlc
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\101142ts\Desktop\github\PlaystoreDownloader\playstoredownloader\cli\__main__.py", line 5, in <module>
    cli()
  File "C:\Users\101142ts\Desktop\github\PlaystoreDownloader\playstoredownloader\cli\cli.py", line 8, in cli
    main(**vars(get_cmd_args()))
  File "C:\Users\101142ts\Desktop\github\PlaystoreDownloader\playstoredownloader\downloader\main.py", line 25, in main
    return download_packages(package, blobs, split_apks, credentials, out_dir, tag)
  File "C:\Users\101142ts\Desktop\github\PlaystoreDownloader\playstoredownloader\downloader\main.py", line 30, in download_packages
    return MultiDownloader(packages, downloader).download()
  File "C:\Users\101142ts\Desktop\github\PlaystoreDownloader\playstoredownloader\downloader\multi_downloader.py", line 26, in download
    raise DownloadError()
playstoredownloader.downloader.downloader.DownloadError`

I printed the contents of response.text and it looks like I'm not getting a normal cookie.

`SID=BAD_COOKIE
LSID=BAD_COOKIE
Auth=EAi5O4fhHiOUalII18GXSMCoo17YDcvraVMqYqeVg0kw1_kuAdXMUxB6tRcR7Ag.
services=mail,hist,multilogin,friendview,cl,android`

Environment is python3.97

**Comment by ClaudiuGeorgiu** [comment]
Hi, that's strange, may be somewhat related to #55. Currently I can't replicate, but I'll update the issue in case I get the same error.

**Comment by gaoshanquan** [comment]
I also met the same problem as you before, and finally I found it was because my Android ID is wrong.  According to the README of the project, I downloaded the app Device ID to check my Android ID, but I mistakenly took Android Device ID as my Android ID, and the same mistake as yours happened when I ran the program.  
You can obtain the ANDROID ID by installing the Device ID application on your device, then copy the string corresponding to Google Service Framework (GSF) (use this string instead of the Android Device ID presented by the application).

**Comment by 89z** [comment]
I have an alternate tool that can create GSF ID:

~~~
googleplay -d
~~~

https://github.com/89z/googleplay

**Comment by 101142TS** [comment]
> I also met the same problem as you before, and finally I found it was because my Android ID is wrong. According to the README of the project, I downloaded the app Device ID to check my Android ID, but I mistakenly took Android Device ID as my Android ID, and the same mistake as yours happened when I ran the program. You can obtain the ANDROID ID by installing the Device ID application on your device, then copy the string corresponding to Google Service Framework (GSF) (use this string instead of the Android Device ID presented by the application).

You are right! Now I can download the app normally, thanks!
